### ISSUE TITLE
No new items after Wed, 25 May 2016

### ISSUE THREAD

**Issue by jarjarbings72000** [majodev/sjgrabber#10]
Hallo,
seit ca. 2 Tagen funktioniert der sjgrabber mit serienjunkies.org nicht mehr.
Diese haben Ihre Homepage neu gestaltet.
Kann man mit einem Update rechnen?

LG
jarjar

**Comment by patpowerman** [comment]
+1 
(so much work to search all the tv-shows manually...)

**Comment by jarjarbings72000** [comment]
@patpowerman .. Was ist dein Problem.
Natürlich ist das keine Arbeit dies manuell zu machen!
Aber wenn es dafür ein Tool gibt und es nicht mehr funktioniert, kann man doch freundlicherweise dem Programierer bescheid geben.

**Comment by patpowerman** [comment]
Du verstehst mich falsch .-)
Erstens habe ich mit +1 klar zum Ausdruck gebracht, dass ich Dein Problem teile und eine Lösung ebenfalls unterstütze. 
Zweitens habe ich nur geschrieben, dass es sehr viel Arbeit macht, all das manuell zu machen - eben ohne das funktionierende Tool.

Zynismus **kann** man in meiner Aussage erkennen, **muss** man aber nicht.
Das nächste Mal schreibe ich wohl lieber:

me too

**Comment by majodev** [comment]
Hi!

Sorry, can't fix this currently, it seems like they decided to discontinue their [RSS-feed](http://serienjunkies.org/xml/feeds/episoden.xml) or have failed to properly migrate its generation. The last entry is from `Wed, 25 May 2016 09:15:01 +0200`. 

However, grabbing links still works (their redesign does not affect this procedure), but only for the current **old** items in their RSS-feed...

**Comment by patpowerman** [comment]
Thank you for your answer, majodev!

Actually, their RSS-Feeds show items until 30.05.2016. But - as an example:
[ENGLISCH] Penny.Dreadful.S03E05.This.World.Is.Our.Hell.German.DD51.DL.1080p.NetflixHD.x264-TVS
Montag, 30. Mai 2016 00:00
is not recognized by SJGrabber (the last item in my list was ...S03E04...)

Is this still a problem in the RSS-Feed?

**Comment by patpowerman** [comment]
It seems to work now! 
*happy*

**Comment by majodev** [comment]
awesome, thx for the bump!
closing...
