### ISSUE TITLE
 error: Cannot save data error: QuotaExceededError

### ISSUE THREAD

**Issue by patpowerman** [majodev/sjgrabber#8]
Today I got this error after starting SJgrabber:
error: Cannot save data error: QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'PRODUCTIVE_items' exceeded the quota.

What can I do?

**Comment by majodev** [comment]
Hi pat!

There is a limit in place to disallow saving data, when the database will get more than 500MB in size. It looks like you've exceeded this limit. Please use the "wipe it" function ("erase data and reset SJgrabber") to get a new database and clear the old one (attention: you will lose your grabbing history)

Sorry for this inconvenience, I'll might fix this by reducing the memory footprint in future versions.

**Comment by patpowerman** [comment]
Thanks for the fast answer!
It seems, a real SJ can reach this limit .-))

Just to be sure: If I "erase data and reset SJgrabber", I'm going to lose all my starred TV-Shows and Filters?

**Comment by majodev** [comment]
Yeah sorry, you'll have to remember them... :/

**Comment by patpowerman** [comment]
No way to manually copy & paste or extract them?
I have added over 40 TV-Shows...

**Comment by majodev** [comment]
If you want to get your hand dirty, you can do the following:

1. Download this [debug build of SJgrabber](https://dl.dropboxusercontent.com/u/2624630/_web/sjgrabber_workaround.zip) (Windows only node-webkit wrapper included).
2. Extract the archive, then open the application by dragging `SJgrabber_debug.nw` over `nw.exe`
![sjgrabber_debug](https://cloud.githubusercontent.com/assets/2149883/7354466/f2ca7f1a-ed1b-11e4-8e5d-eb090633821e.png)
3. Open the developer-tools (via the hamburger icon in the top-right corner) and input the following:
```
localstorage.PRODUCTIVE_items = "";
NWAPP.closeApplicationNow();
```
![sjgrabber_debug_2](https://cloud.githubusercontent.com/assets/2149883/7354494/182ab96e-ed1c-11e4-8eb4-d85f838ff351.png)

You can now delete this debug-build. All starred keywords and global settings should remain unharmed while all previous release items should have been deleted (fixing the `QuotaExceededError `).

If you use another platform than Windows, you need to download the [node-webkit wrapper](https://github.com/nwjs/nw.js/#downloads) for your platform (use version 0.8.6) and drag the `SJgrabber_debug.nw` onto this application. Then follow the above steps.

Sorry for the inconvenience, I'll try to address these issue in a future version.

**Comment by patpowerman** [comment]
Great! Thank you very much! SJgrabber works fine (again).

If I can help to test your next version including some kind of "delete old stuff but not the starred keywords or filters", just let me know.

**Comment by patpowerman** [comment]
Today, this message appears again...
If I have a christmas wish: Could you please let us clear the Quota with a button in the settings?

**Comment by majodev** [comment]
Christmas wish completed. Sorry that it took so long.

**Comment by patpowerman** [comment]
Jingle Bells and thanks a lot!
